name: Tests

env:
  NODE_VERSION: 16

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test-unit:
    name: Karma unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Using node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Test
        run: npm run test:lib

  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Using node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run demo
          wait-on: 'http://localhost:4200'
          project: ./e2e
          browser: chrome
          quiet: true
          headless: true
